classdef (Abstract) Constants

    properties (Constant)
        %-----------------------------------------------------------------%
        appName       = 'SCH'
        appRelease    = 'R2024a'
        appVersion    = '0.10'

        windowSize    = [1244, 660]
        windowMinSize = [ 880, 660]
        
        xDecimals     = 5
        floatDiffTol  = 1e-5

        cacheColumns  = {'Homologação', 'Solicitante | Fabricante', 'Modelo | Nome Comercial'}
        staticColumns = {'Homologação', 'Tipo', 'Solicitante', 'CNPJ/CPF', 'Fabricante', 'Modelo', 'Nome Comercial', 'Situação'}        
        allColumns    = {'Data da Homologação', 'Homologação', 'Solicitante', 'CNPJ/CPF', 'Certificado de Conformidade Técnica',                ...
                         'Data do Certificado de Conformidade Técnica', 'Data de Validade do Certificado', 'Código de Situação do Certificado', ...
                         'Situação do Certificado', 'Código de Situação do Requerimento', 'Situação', 'Fabricante', 'Modelo', 'Nome Comercial', ...
                         'Categoria do Produto', 'Tipo', 'IC_ANTENA', 'IC_ATIVO', 'País do Fabricante', 'CodUIT', 'CodISO'}
        widthColumns  = { 90, ... % 'Data da Homologação'
                         110, ... % 'Homologação'
                      'auto', ... % 'Solicitante'
                         110, ... % 'CNPJ/CPF'
                         110, ... % 'Certificado de Conformidade Técnica'
                          90, ... % 'Data do Certificado de Conformidade Técnica'
                          90, ... % 'Data de Validade do Certificado' 
                          55, ... % 'Código de Situação do Certificado'
                         150, ... % 'Situação do Certificado'
                          55, ... % 'Código de Situação do Requerimento'
                         150, ... % 'Situação'
                      'auto', ... % 'Fabricante'
                         150, ... % 'Modelo'
                         150, ... % 'Nome Comercial'
                          55, ... % 'Categoria do Produto'
                         300, ... % 'Tipo'
                          55, ... % 'IC_ANTENA'
                          55, ... % 'IC_ATIVO'
                         110, ... % 'País do Fabricante'
                          55, ... % 'CodUIT' 
                          55}     % 'CodISO'

        notesColumns  = {'ID', 'DataHora', 'Computador', 'Usuário', 'Homologação', 'Atributo', 'Valor', 'Situação'}

        tblStyle_row  = uistyle('BackgroundColor', [.96,.96,.96])                            % Row striping
        tblStyle_col  = uistyle('BackgroundColor', [.24 .47 .85], 'FontColor', 'white')      % Table primary column background
        tblStyle_cell1= uistyle('Icon', 'Edit_18x18GT.png', 'IconAlignment', 'rightmargin')  % Cell annotation icon
        tblStyle_cell2= uistyle('Icon', 'Edit_18x18WT.png', 'IconAlignment', 'rightmargin')  % Cell annotation icon
        
        listBoxStyle  = uistyle('FontColor', [.65,.65,.65], 'Icon', 'LockClose_18x18G.png', 'IconAlignment', 'leftmargin')
    end

    
    methods (Static = true)
        %-----------------------------------------------------------------%
        function fileName = DefaultFileName(userPath, Prefix, Issue)
            fileName = fullfile(userPath, sprintf('%s_%s', Prefix, datestr(now, 'yyyy.mm.dd_THH.MM.SS')));

            if Issue > 0
                fileName = sprintf('%s_%d', fileName, Issue);
            end
        end


        %-----------------------------------------------------------------%
        function d = english2portuguese()
            names  = ["AntennaHeight", ...
                      "Azimuth", ...
                      "Band", ...
                      "BitsPerSample", ...
                      "Count", ...
                      "DataPoints", ...
                      "Description", ...
                      "Distance", ...
                      "Elevation", ...
                      "Family", ...
                      "File", ...
                      "FileVersion", ...
                      "Frequency", ...
                      "gpsType", ...
                      "Height", ...
                      "Installation", ...
                      "IntegrationFactor", ...
                      "LevelUnit", ...
                      "Location", ...
                      "LocationSource", ...
                      "Memory", ...
                      "MetaData", ...
                      "Name", ...
                      "nData", ...
                      "nSweeps", ...
                      "Observation", ...
                      "ObservationSamples", ...
                      "ObservationTime", ...
                      "ObservationType", ...
                      "Polarization", ...
                      "Position", ...
                      "Proeminence", ...
                      "Receiver", ...
                      "Resolution", ...
                      "RevisitTime", ...
                      "RFMode", ...
                      "Service", ...
                      "Sync", ...
                      "Station", ...
                      "StepWidth", ...
                      "switchPort", ...
                      "Target", ...
                      "Task", ...
                      "taskType", ...
                      "Type", ...
                      "TraceIntegration", ...
                      "TraceMode", ...
                      "TrackingMode"];
            values = ["Altura da antena", ...
                      "Azimute", ...
                      "Banda", ...
                      "Codificação", ...
                      "Qtd. amostras", ...
                      "Pontos por varredura", ...
                      "Descrição", ...
                      "Distância", ...
                      "Elevação", ...
                      "Família", ...
                      "Arquivo", ...
                      "Arquivo", ...
                      "Frequência", ...
                      "GPS", ...
                      "Altura", ...
                      "Instalação", ...
                      "Integração", ...
                      "Unidade", ...
                      "Localidade", ...
                      "Fonte", ...
                      "Memória", ...
                      "Metadados", ...
                      "Nome", ...
                      "Qtd. fluxos", ...
                      "Qtd. varreduras", ...
                      "Observação", ...
                      "Amostras a coletar", ...
                      "Observação", ...
                      "Tipo de observação", ...
                      "Polarização", ...
                      "Posição", ...
                      "Proeminência", ...
                      "Receptor", ...
                      "Resolução", ...
                      "Tempo de revisita", ...
                      "Modo RF", ...
                      "Serviço", ...
                      "Sincronismo", ...
                      "Estação", ...
                      "Passo da varredura", ...
                      "Porta da matriz", ...
                      "Alvo", ...
                      "Tarefa", ...
                      "Tipo de tarefa", ...
                      "Tipo", ...
                      "Integração", ...
                      "Traço", ...
                      "Modo de apontamento"];
        
            d = dictionary(names, values);
        end
    end
end