function appVersion = envVersion(rootFolder)

    appName    = class.Constants.appName;
    appVersion = struct('Machine', '', ...
                        'Matlab',  '', ...
                        appName,   struct('Release',    class.Constants.appRelease, ...
                                          'Version',    class.Constants.appVersion, ...
                                          'RootFolder', rootFolder));

    % OS
    appVersion.Machine = struct('Platform',     ccTools.fcn.OperationSystem('platform'), ...
                                'Version',      ccTools.fcn.OperationSystem('ver'),      ...
                                'computerName', getenv('COMPUTERNAME'),                  ...
                                'userName',     getenv('USERNAME'));

    % OpenGL
    graphRender = '';
    try
        graphRender = opengl('data');
        graphRender = rmfield(graphRender, {'MaxTextureSize', 'Visual', 'SupportsGraphicsSmoothing', 'SupportsDepthPeelTransparency', 'SupportsAlignVertexCenters', 'Extensions', 'MaxFrameBufferSize'});
    catch
    end

    % MATLAB    
    [matVersion, matReleaseDate] = version;
    matProducts = struct2table(ver);
    appVersion.Matlab  = struct('Version',  sprintf('%s (Release date: %s)', matVersion, matReleaseDate), ...
                                'Path',     matlabroot,                                                   ...
                                'Products', strjoin(matProducts.Name + " v. " + matProducts.Version, ', '), ...
                                'openGL',   graphRender);

end