classdef (Abstract) Constants

    properties (Constant)
        %-----------------------------------------------------------------%
        appName       = 'SCH'
        appRelease    = 'R2024a'
        appVersion    = '1.20.0'

        windowSize    = [1244, 660]
        windowMinSize = [ 880, 660]
    end


    methods (Static = true)
        %-----------------------------------------------------------------%
        function d = english2portuguese()
            names  = ["FileName", ...
                      "TempFileName", ...
                      "Period", ...
                      "Content", ...
                      "Table", ...
                      "ReceitaFederal", ...
                      "OrdinaryTable", ...
                      "Origin", ...
                      "ReadOrdinaryTable", ...
                      "CreateCustomTable", ...
                      "Warnings", ...
                      "UF"];
            values = ["Arquivo", ...
                      "Arquivo temporário", ...
                      "Período", ...
                      "Conteúdo", ...
                      "Registros", ...
                      "Receita Federal", ...
                      "Registros ordinários", ...
                      "Origem", ...
                      "Registros ordinários lidos", ...
                      "Tabelas customizadas", ...
                      "Alertas do processo de leitura", ...
                      "Unidade da Federação"];
        
            d = dictionary(names, values);
        end
    end

end